### ISSUE TITLE
which work is this code related to ?

### ISSUE THREAD

**Issue by moshicaixi** [edshkim98/GAGCN#1]
Hi, does this code rely on the work below? Because i can't find the work "GAGCN" written in the readme file.  
![image](https://user-images.githubusercontent.com/63298919/158132060-bcb8f735-ad43-470e-b6f2-96347136c309.png)

**Comment by edshkim98** [comment]
Hello, thank you for your interest.
This code is not specifically related to the paper, but it was for my master thesis earlier ago.
So, it is quite different to the paper and the performance is not the same as well.
The code for AGCN is currently in private.

**Comment by moshicaixi** [comment]
ok, thanks  for your reply. Have a good day.
